#include "butterlowpass.h"

/*
 * This file is autogenerated. Please do not modify directly as changes may be
 * overwritten.
 */

namespace {
    // Butter lowpass filter
    // order: 4
    // cutoff freq: 5.0
    // sample freq: 200.0
    const double a[] = { 1.0,-3.58973388711,4.85127588252,-2.92405265616,0.663010484386 };
    const double b[] = { 3.12389769171e-05,0.000124955907668,0.000187433861502,0.000124955907668,3.12389769171e-05 };
} // namespace

ButterLowpass::ButterLowpass(): _x{0.0f}, _y{0.0f}, _n{0} { }

float ButterLowpass::filter(float sample) {
    _x[_n] = sample;
    _y[_n] = b[0]*_x[_n];
    for (int i = 1; i < _size; ++i) {
        _y[_n] += b[i]*_x[(_n - i + _size) % _size]
            - a[i]*_y[(_n - i + _size) % _size];
    }

    float result = _y[_n];
    _n = (_n + 1) % _size;
    return result;
}