#ifndef CHEBY1LOWPASS_H
#define CHEBY1LOWPASS_H

/*
 * This file is autogenerated. Please do not modify directly as changes may be
 * overwritten.
 */

class Cheby1Lowpass {
private:
    static const int _size = 4 + 1;
    double _x[_size]; // input
    double _y[_size]; // output
    int _n; // current array index

public:
    Cheby1Lowpass();
    float filter(float sample);
};

#endif // CHEBY1LOWPASS_H