//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pose.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BicyclePoseMessage")]
  public partial class BicyclePoseMessage : global::ProtoBuf.IExtensible
  {
    public BicyclePoseMessage() {}
    
    private uint _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _yaw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private float _roll;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roll", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float roll
    {
      get { return _roll; }
      set { _roll = value; }
    }
    private float _pitch;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private float _steer;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"steer", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float steer
    {
      get { return _steer; }
      set { _steer = value; }
    }
    private float _rear_wheel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rear_wheel", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rear_wheel
    {
      get { return _rear_wheel; }
      set { _rear_wheel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}